### ISSUE TITLE
getrawtransaction optional arguments

### ISSUE THREAD

**Issue by baloian** [vansergen/rpc-bitcoin#34]
Why `getrawtransaction` requires `blockhash` argument?

Based on the RPC documentation it is an optional argument. See: https://developer.bitcoin.org/reference/rpc/getrawtransaction.html

Am I missing something?

**Comment by vansergen** [comment]
@baloian  It is an [optional](https://github.com/vansergen/rpc-bitcoin/blob/ace0f6889d2454c741600bd2a85de410ca494f1d/src/rpc.ts#L167)

**Comment by baloian** [comment]
@vansergen Thank you. I got the issue. I was passing an empty string, though, I should have passed undefined value.

I am closing the issue.
